/* ORDER BY */
SELECT
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
--   ORDER BY MENU_PRICE ASC; -- 오름차순 정렬(안써도 자동으로 됨)
ORDER BY MENU_PRICE; -- ORDER BY를 쓰면 정렬기능

SELECT
       MENU_CODE
     , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
ORDER BY MENU_PRICE DESC; -- 내림차순정렬 (꼭 작성해야 함)

SELECT
       MENU_CODE
	 , MENU_NAME
     , MENU_PRICE
  FROM TBL_MENU
ORDER BY MENU_PRICE DESC,
		 MENU_NAME ASC;
         
SELECT
       MENU_CODE
	 , MENU_PRICE
     , MENU_CODE * MENU_PRICE
  FROM TBL_MENU
ORDER BY MENU_CODE * MENU_PRICE DESC;

SELECT FIELD('A', 'A', 'B', 'C');
SELECT FIELD('B', 'A', 'B', 'C');

SELECT
       FIELD(ORDERABLE_STATUS, 'N', 'Y')
  FROM TBL_MENU;
  
-- 오름차순 시 NULL은 처음으로 호출
SELECT
       CATEGORY_CODE
	 , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
ORDER BY REF_CATEGORY_CODE;

-- 오름차순 시 NULL을 마지막으로 호출
SELECT
       CATEGORY_CODE
	 , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
ORDER BY REF_CATEGORY_CODE IS NULL; 

-- 내림차순 시 NULL을 마지막으로 호출
SELECT
       CATEGORY_CODE
	 , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
ORDER BY REF_CATEGORY_CODE DESC;

-- 내림차순 시 NULL을 처음으로 호출
SELECT
       CATEGORY_CODE
	 , CATEGORY_NAME
     , REF_CATEGORY_CODE
  FROM TBL_CATEGORY
ORDER BY REF_CATEGORY_CODE IS NULL DESC, REF_CATEGORY_CODE DESC;